### ISSUE TITLE
QuizID now hashed and created by a javascript file

### ISSUE THREAD

**Issue by LostQuasar** [reteps/quizizz-bot#1]
I've looked through it and it's not working I've also updated some of the classes on the buttons.

**Comment by reteps** [comment]
huh. can you give me a quizizz link to test?

**Comment by LostQuasar** [comment]
https://quizizz.com/join-game 
ID:688944

**Comment by reteps** [comment]
what is the quizizz name so i can look it up?

**Comment by LostQuasar** [comment]
https://quizizz.com/admin/quiz/5c18ca88ba6a61001abc9139/merry-christmas-math sorry

**Comment by LostQuasar** [comment]
Here are 3 different IDs ive collected they seem to start and end with the same characters
[quizIDs.txt](https://github.com/reteps/quizizz-bot/files/2725775/quizIDs.txt)

**Comment by LostQuasar** [comment]
Now with actual IDs to help decode!!! 
[quizIDs.txt](https://github.com/reteps/quizizz-bot/files/2725879/quizIDs.txt) Adding this to my fork too

**Comment by Skyluro** [comment]
hey guys I don't know much python and web coding, however, if you look at the network section of the inspect element tab you will see a piece of data which has the gameID. It's called "recommend?quizid=" (quizid after = ). All you have to do is log the network traffic before and after the "Enter Game" button is clicked. I don't know if it is possible to log that or if google is decrypting it but, I hope it helps. (plz no hate)

**Comment by Skyluro** [comment]
figured out parsing with some of the most sloppy coding(lul). Either way, it works, gonna try and put it into ur bot and clean it up. The script for GameID is linked below

[getQuizID.txt](https://github.com/reteps/quizizz-bot/files/3052649/getQuizID.txt)

**Comment by LostQuasar** [comment]
@Skyluro Reteps timings are off, try my fork's code it worked before just couldn't find the quizID

**Comment by reteps** [comment]
It may be better to rely on waiting for elements to appear or page load
rather than arbitrary timings.

**Comment by LostQuasar** [comment]
Yea I think that makes more sense, also I don't see a point in adding a GUI. Timings seem to be the only issue right now

**Comment by reteps** [comment]
I don’t know, a JavaScript based concept may let non-coders use the program.

**Comment by Skyluro** [comment]
Yea I am working on it, I did it over the weekend so not everything is perfect. Unfortunately, I know little javascript and just started python so it may take a bit of time. Thanks for the suggestions I'll look into them over my spring break next week.

**Comment by reteps** [comment]
Great work. If you can manage to find the ID without an instance of chrome running, I will really be impressed!

**Comment by Skyluro** [comment]
Should be possible by using just the one for the game and not the other since it just logs network data while connecting to the game. Should just be some easy re-organization. Might see if I can do it tonight

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Skyluro** [comment]
Ok, got it working w/ just the game window. Will work on the timing later.

**Comment by Skyluro** [comment]
Timing should be much better now

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by LostQuasar** [comment]
Works like a charm. maybe consider adding a random delay to make it less
obvious. maybe even an option to get one or two wrong

**Comment by LostQuasar** [comment]
Issue resolved?
