### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by porozzy** [reteps/quizizz-bot#6]
Traceback (most recent call last):
  File "/Users/oozzypor/Documents/TGML2 - The Factory/quizizz-bot/quizizz-bot.py", line 2, in <module>
    import os, time, json, requests, sys, random, string, tkinter, subprocess, tempfile
ModuleNotFoundError: No module named 'requests'
[Finished in 0.1s with exit code 1]
[shell_cmd: python3 -OO -u "/Users/oozzypor/Documents/TGML2 - The Factory/quizizz-bot/quizizz-bot.py"]
[dir: /Users/oozzypor/Documents/TGML2 - The Factory/quizizz-bot]
[path: /Library/Frameworks/Python.framework/Versions/3.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/oozzypor/developer/flutter/bin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Library/Frameworks/Python.framework/Versions/3.7/bin]

**Comment by LostQuasar** [comment]
You need to pip install requests
