### ISSUE TITLE
Where are answer in source code?

### ISSUE THREAD

**Issue by chrisovato** [reteps/quizizz-bot#7]
Hi, 

could you say me where in source code of the quizizz page are the answer for the quiz?

**Comment by Skyluro** [comment]
They aren’t in the source code

**Comment by chrisovato** [comment]
so where are they?

**Comment by Skyluro** [comment]
Hmm forgot the link. Basically, every game is given a code corresponding with its and key

**Comment by Skyluro** [comment]
And if u visits the right link (that has that quiz specific code in it) it sends over the ans

**Comment by Skyluro** [comment]
U can look at the code if u wanna know more. It’s been a while since I’ve touched this

**Comment by chrisovato** [comment]
So it is finding gameID and then it going to the url with this gameID, but from where does this script takes this gameID?

**Comment by Skyluro** [comment]
Do you mean what does the script do with the gameID?

**Comment by chrisovato** [comment]
I mean from where your script takes gameID?

**Comment by Skyluro** [comment]
the code I am talking about is diff from the gameID u enter into the website

**Comment by chrisovato** [comment]
I mean from where your script takes gameID to this function : 
https://github.com/reteps/quizizz-bot/blob/master/quizizz-bot.py#L21

**Comment by reteps** [comment]
The line right below.
https://github.com/reteps/quizizz-bot/blob/master/quizizz-bot.py#L22
